apiVersion: apps/v1
kind: Deployment
metadata:
  name: server-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      component: server
  template:
    metadata:
      labels:
        component: server
    spec:
      containers:
        - name: server
          image: sanyamgupta23/multi-server
          ports:
            - containerPort: 8000
          env:
            - name: REDIS_HOST
              value: redis-cluster-ip-srv
            - name: REDIS_PORT
              value: "6379"
            - name: POSTGRES_HOST
              value: postgres-cluster-ip-srv
            - name: POSTGRES_DATABASE_NAME
              value: postgres
            - name: POSTGRES_USER
              value: postgres
            - name: POSTGRES_PORT
              value: "5432"
          envFrom:
            - secretRef:
                name: pgpassword
